name: 'Docker Build/Tag/Push'
description: 'Github action to build, tag, and then push a Docker image'
inputs:
  aws-access-key-id:
    description: 'The AWS access key ID to use for pushing the image'
    required: true
  aws-secret-access-key:
    description: 'The AWS secret access key to use for pushing the image'
    required: true
  aws-region:
    description: 'The AWS region that holds the ECR repository'
    required: true
  ecr-repository:
    description: 'The name of the ECR repository'
    required: true
runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials
      id: aws-credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}

    - name: Authenticate with Amazon ECR
      id: ecr-login
      uses: aws-actions/amazon-ecr-login@v1

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: |
          ${{ steps.ecr-login.outputs.registry }}/${{ inputs.ecr-repository }}
        tags: |
          type=ref,event=branch
          type=sha

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to ECR
      uses: docker/login-action@v1
      with:
        registry: ${{ steps.ecr-login.outputs.registry }}

    - name: Docker Build and Push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ steps.meta.outputs.tags }}
